## PROGRAMS ON NUMPY

In [6]:
import numpy as np

### Numpy program to multiply two arrays of same size element-by-element

In [6]:
a=np.array([[7,8,1],[5,6,2]])
b=np.array([[1,2,3],[4,5,6]])
c=a*b
d=np.multiply(a,b)
print(c)
print(d)

[[ 7 16  3]
 [20 30 12]]
[[ 7 16  3]
 [20 30 12]]


### Numpy program to find missing data in a given array

In [26]:
arr1 = np.array([2,8,5,86,np.nan,np.nan])

np.where(np.isnan(arr1))

(array([4, 5], dtype=int64),)

### Numpy program to test whether each element of 1-D array present in a second array

In [12]:
f=np.array([1,2,3])
g=np.array([1,2,3])
i=np.array([1,2,4])
h=np.array_equal(f,g)
j=np.array_equal(f,i)
print(h)
print(j)

True
False


### Numpy program to save numpy array in a text file

In [15]:
with open("file1.txt","w") as file1:
    arr1 = np.array(["1","2","3","4","5"])
    for i in arr1:
        file1.write(i)
        file1.write(" ")

### Numpy program to create a 1-D array of 30 evenly spaced elements between 2.5 to 6.5

In [18]:
random= np.random.uniform(2.5,6.5,[30,])
random

array([3.92041842, 2.88076164, 4.10046913, 3.52308019, 6.39315055,
       6.39003626, 4.92431972, 3.87537551, 3.97138578, 2.73519588,
       3.42057142, 3.09484171, 6.20140142, 6.08712157, 5.0814917 ,
       3.5132118 , 5.37110776, 3.89924332, 3.4557231 , 6.43685655,
       3.35402606, 5.88904382, 6.16701069, 6.42468949, 4.46902678,
       5.75359405, 6.35247551, 5.47867961, 4.75293584, 5.55478068])

## PROGRAMS ON PANDAS

In [2]:
import pandas as ps

### Pandas program to convert Series of lists to one list

In [27]:
a = ps.Series([1,5,2,4,4],[3,4,6,4,3])
print(a)

3    1
4    5
6    2
4    4
3    4
dtype: int64


### Pandas program to create subset of given series based on value and condition

In [29]:
df1 = ps.Series([2,5,5,3,3,4,34,43])

df1[df1%2==0]

0     2
5     4
6    34
dtype: int64

### Pandas program to display most frequent value in a given series and replace everything else as Other in the series.

In [30]:
df1 = ps.Series([78,98,56,76,32,78,98,78])
a=df1.mode()[0]
df1[df1!=a]='other'
df1

0       78
1    other
2    other
3    other
4    other
5       78
6    other
7       78
dtype: object

### Pandas program to find the positions of numbers that are multiples of 5 of agiven series.

In [34]:
df1 = ps.Series([5,10,64,34,54])

df1[df1%5==0].index

Index([0, 1], dtype='int64')

### Write a Pandas program to calculate the number of characters in each word in a given series.

In [33]:
df2 = ps.Series(['Hi','I','Am',"Ravi",'Prakash'])

for i in df2:
    print(i,len(i))

Hi 2
I 1
Am 2
Ravi 4
Prakash 7


### Pandas program to convert year-month string to dates adding a specified day of the month.

In [35]:
from dateutil.parser import parse
date_series = ps.Series(['Jan 2020', 'Feb 2021', 'Mar 2022', 'Apr 2023', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2020
1    Feb 2021
2    Mar 2022
3    Apr 2023
4    May 2019
dtype: object

New dates:
0   2020-01-11
1   2021-02-11
2   2022-03-11
3   2023-04-11
4   2019-05-11
dtype: datetime64[ns]


### Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [38]:
dict1 = {
    'Students':['Ravi',"Prakash","Gupta"],
    'Age':[19,21,19],
    'Marks':[230,235,260],
    'Out of':[300,300,300]
}

ds = ps.DataFrame(dict1,index=['Student1','Student2','Student3'])
ds

Students  Age  Marks  Out of
Student1     Ravi   19    230     300
Student2  Prakash   21    235     300
Student3    Gupta   19    260     300

### Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [41]:
dict1 = {
    'Students':['Ravi',"Prakash","Gupta"],
    'Age':[19,21,19],
    'Marks':[230,235,260],
    'Out of':[300,300,300],
    'No of Attempts':[1,2,1]
}
ds1 = ps.DataFrame(dict1)

ds1[ds1['No of Attempts']>1]

Students  Age  Marks  Out of  No of Attempts
1  Prakash   21    235     300               2

### Pandas program to append a new row k to data frame with given values for each column. Now delete the new row and return the original DataFrame.

In [8]:
dict1 = {
    'Students':['Ravi',"Prakash","Gupta"],
    'Age':[19,21,19],
    'Marks':[230,235,260],
    'Out of':[300,300,300]
}
df4 = ps.DataFrame(dict1)

df4['k'] = [54,43,54]

print(df4)

df4.drop(['k'],axis=1)
df4

  Students  Age  Marks  Out of   k
0     Ravi   19    230     300  54
1  Prakash   21    235     300  43
2    Gupta   19    260     300  54


Students  Age  Marks  Out of   k
0     Ravi   19    230     300  54
1  Prakash   21    235     300  43
2    Gupta   19    260     300  54

### Pandas program to sort the DataFrame first by name in descending order,then by score in ascending order.

In [50]:
dict1 = {
    'Students':['Ravi',"Prakash","Gupta"],
    'Age':[19,21,19],
    'Marks':[230,235,260],
    'Out of':[300,300,300],
}
df3 = ps.DataFrame(dict1)

df3 = df3.sort_values(['Students','Marks'],ascending=[False,True])

df3

Students  Age  Marks  Out of
0     Ravi   19    230     300
1  Prakash   21    235     300
2    Gupta   19    260     300

### Pandas program to replace the &#39;qualify&#39; column contains the values &#39;yes&#39; and no with True and False.

In [3]:
dict1 = {
    'Students':['Ravi',"Prakash","Gupta"],
    'Age':[19,21,19],
    'Marks':[230,235,260],
    'Out of':[300,300,300],
    'Qualify':['Yes','Yes','No']
}

ds2 = ps.DataFrame(dict1)

ds2['Qualify']= ds2['Qualify'].replace({'Yes':True,'No': False})
ds2

Students  Age  Marks  Out of  Qualify
0     Ravi   19    230     300     True
1  Prakash   21    235     300     True
2    Gupta   19    260     300    False

### Pandas program to remove infinite values from a given DataFrame.

In [7]:
dict2 = {
    'X':[1,3,4,6,np.inf],
    'Y':[32,5,np.inf,8,98]
}

ds3 = ps.DataFrame(dict2)

ds3 = ds3.replace({np.inf:np.NaN})

ds3 = ds3.dropna()
ds3

X     Y
0  1.0  32.0
1  3.0   5.0
3  6.0   8.0